services:
  postgres:
    image: postgres:16-alpine
    container_name: uc_teklif_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: uc_teklif
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - uc_teklif_pg_data:/var/lib/postgresql/data

volumes:
  uc_teklif_pg_data:

